import { uiIcon } from '../../packages/lib/src/dom/ui-icon';
import type { UiIcon } from '../../packages/lib/src/dom/ui-icon';

const ja = {
  settings: '設定',
  details: '動画の詳細',
  close: '閉じる',
  quality: '画質',
  previous: '前の動画',
  play: '再生',
  pause: '一時停止',
  next: '次の動画',
  repeat: 'リピート',
  ab: 'ABリピート',
  setA: '開始位置Aを設定',
  setB: '終了位置Bを設定',
  clearAB: 'ABリピートを解除',
  invalidB: '終了位置Bは開始位置Aより後に設定してください',
  speed: '再生速度',
  volume: '音量',
  mute: 'ミュート',
  fullscreen: '全画面',
  comments: 'コメント表示',
  info: '動画情報',
  related: '関連動画',
  comment: 'コメント',
  playlist: 'プレイリスト',
  date: '投稿日',
  views: '再生数',
  commentCount: 'コメント数',
  mylists: 'マイリスト数',
  likes: 'いいね数',
  auto: '自動',
  more: 'その他操作',
  reload: '再読み込み',
  capture: 'コメント付き画像を保存',
  original: '公式視聴ページ',
  helpAB: '1回目でA、2回目でB、3回目で解除',
  lockDetails: '詳細パネルを固定',
  unlockDetails: '詳細パネルの固定を解除',
};
const en: typeof ja = {
  settings: 'Settings',
  details: 'Video details',
  close: 'Close',
  quality: 'Video quality',
  previous: 'Previous video',
  play: 'Play',
  pause: 'Pause',
  next: 'Next video',
  repeat: 'Repeat',
  ab: 'A–B repeat',
  setA: 'Set start A',
  setB: 'Set end B',
  clearAB: 'Clear A–B repeat',
  invalidB: 'Set B after A',
  speed: 'Playback speed',
  volume: 'Volume',
  mute: 'Mute',
  fullscreen: 'Fullscreen',
  comments: 'Show comments',
  info: 'Video info',
  related: 'Related videos',
  comment: 'Comments',
  playlist: 'Playlist',
  date: 'Posted',
  views: 'Views',
  commentCount: 'Comments',
  mylists: 'Mylists',
  likes: 'Likes',
  auto: 'Auto',
  more: 'More controls',
  reload: 'Reload',
  capture: 'Save image with comments',
  original: 'Official watch page',
  helpAB: 'First click: A. Second: B. Third: clear.',
  lockDetails: 'Pin details panel',
  unlockDetails: 'Unpin details panel',
};
export const shellText = (language: string): typeof ja => (language.startsWith('ja') ? ja : en);

export type ShellIcon = UiIcon;
export const shellIcon = uiIcon;
export function shellButton(action: string, label: string, icon: ShellIcon, extra = ''): string {
  return `<button type="button" data-shell-action="${action}" title="${label}" aria-label="${label}" ${extra}>${shellIcon(icon)}</button>`;
}
